apiVersion: 1

datasources:
  - name: SQLite
    type: frser-sqlite-datasource
    uid: ff8zarz39a2gwd
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      path: /db/2026_01_02.db
    version: 1
