version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1000:1000"
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=frser-sqlite-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ../db:/db:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
      - ./provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    networks:
      - grafana-network

networks:
  grafana-network:
    driver: bridge

